.eslintignore
.eslintrc.json
.gitignore
README.md
etools-dropdown.html
package.json

- added linting tasks
- linted code
- connects unicef/etools-issues#386

add linting tasks 

---

bower.json
etools-dropdown-multi.html
etools-dropdown.html
mixins/common-mixin.html

- fixed issue with input opening twice
- fixed invisible dropdowns
- connects unicef/etools-issues#1028

Fix dialog issues 

---

README.md
mixins/common-mixin.html

- Made the search string reset on dropdown close
- connects to clubhouse issue 4361

Reset search on dropdown close 

---

styles/esmm-shared-styles.html

Add css mixins 

---

etools-dropdown-multi.html
etools-dropdown.html
mixins/common-mixin.html

fixed an issue with error box being rendered even when valid
[ch4953]

Fix height issues 

---

mixins/common-mixin.html

Fixed an IE issue with the dropdows closing right after being opened [ch4999]

Fix ie closing dropdowns 

---

elements/options-list.html

Fixed an issue with options in the dropdown not being aligned vertically

---

mixins/common-mixin.html

Fixed an issue with the dropdown not closing properly on the esc key

---

elements/selected-options.html
etools-dropdown-multi.html

Fix parent resize issues

---

README.md
etools-dropdown-multi.html
etools-dropdown.html
mixins/common-mixin.html

Reverts unicef-polymer/etools-dropdown#27

Revert "Revert "Added custom selected event to etools-dropdown elem""

---

mixins/common-mixin.html

Fixed an issue with fitInto property not working as expected

---

demo/elements/sigle-selection-demo.html
mixins/common-mixin.html

fixed the limit warning when searching in dropdown [ch7307]

Fix  limit warning

---

bower.json
demo/elements/sigle-selection-demo.html
elements/selected-options.html
etools-dropdown-multi.html
etools-dropdown.html
mixins/common-mixin.html
styles/esmm-shared-styles.html

* fixed styles for selected items on IE [ch5839]
* [ch5485]
* [ch7307] - limit fix
* [ch7585]

dropdown updates

---

bower.json
elements/options-list.html

fix none option style

---

etools-dropdown.js
package.json

Allow 0 as option value

---

etools-dropdown-multi.js
package.json

Fixes to prevent errors in case optionValue parameter doesn't match options field.

Fixes to prevent errors in case optionValue parameter doesn't match options field.

---

mixins/common-mixin.js
package-lock.json
package.json

Delay on open sizing updates, fixes flickering in dialogs

---

etools-dropdown.js
mixins/common-mixin.js
package.json

[ch16146]Go to item that starts with pressed letter

---

package.json
styles/esmm-shared-styles.js

Update focused color

---

mixins/common-mixin.js
package.json

[ch16003] Drop-down Search not tied to search input

[ch16003] Drop-down Search not tied to search input

---

etools-dropdown-multi.js
mixins/common-mixin.js
package.json

Add option to hide close option

Add option to hide close option

---

.eslintrc.json
etools-dropdown.js
package-lock.json
package.json

[ch19962]Fix closing on scroll click & security alerts fixes

---

mixins/common-mixin.js
package.json

[ch21111]Third Party Monitor/Team members/Person responsible drop-downs are empty
fixed limit warning issue

[ch21111]Third Party Monitor/Team members/Person responsible drop-downs are empty

---

mixins/common-mixin.js
package-lock.json
package.json

[ch22599] Intermittent: Scroll blocks in Unicef Sections list and user cannot see last option

[ch22599] Intermittent: Scroll blocks in Unicef Sections list and user cannot see last option

---

etools-dropdown-multi.js
mixins/common-mixin.js
package.json

[ch23150] Intermittent dropdown issues

[ch23150] Intermittent dropdown issues

---

EtoolsDropdownMulti.js
elements/options-list.js
etools-dropdown-multi.d.ts

[ch25290] Multiselect Dropdown UX

[ch25290] Multiselect Dropdown UX

---

EtoolsDropdown.js
EtoolsDropdownMulti.js
elements/selected-options.js
mixins/common-mixin.js

[ch25298] Add slot for info icon to etools-dropdown's label

[ch25298] Add slot for info icon to etools-dropdown's label

---

EtoolsDropdown.js
mixins/common-mixin.js

[ch25780] Invalid message displayed premature at dialog open

[ch25780] Invalid message displayed premature at dialog open

---

.eslintrc.json
.prettierrc
EtoolsDropdown.js
elements/options-list.js
package-lock.json
package.json
styles/esmm-shared-styles.js

[ch25893]Rounded corners/lighter gray & fix formatting

---

EtoolsDropdown.js
EtoolsDropdownMulti.js
analysis.json
elements/options-list.js
mixins/common-mixin.d.ts
mixins/common-mixin.js
package-lock.json
package.json

[ch25941]Infinite scroll

---

elements/selected-options.js
package-lock.json
package.json

[ch25862] Fix label suffix (prevent event bubble)

[ch25862] Fix label suffix (prevent event bubble)

---

EtoolsDropdown.js
package-lock.json
package.json

Fix selecting item from value, [ch27347] Add/Edit Site Specific Location: cannot add Not Active or update to Not Active Sites

Fix selecting item from value, [ch27347] Add/Edit Site Specific Location: cannot add Not Active or update to Not Active Sites

---

mixins/common-mixin.js
package-lock.json
package.json

[ch27477] [etools-dropdown] When Request is In Progress do not show msg to Scroll down

[ch27477] [etools-dropdown] When Request is In Progress do not show msg to Scroll down

---

.circleci/config.yml

[ch26784]Config ci linting job

---

EtoolsDropdown.js

[ch27575] EtoolsDropDown fix error on unselecting item

[ch27575] EtoolsDropDown fix error on unselecting item

---

EtoolsDropdown.js
package-lock.json
package.json

[ch27549]Allow select of item with value 0

---

mixins/common-mixin.js
package-lock.json
package.json

[ch28004]Fix warning msg

---

EtoolsDropdown.js
README.md
package-lock.json
package.json
styles/esmm-shared-styles.js

[ch28938] [Fix Content Style] Language drop-down

[ch28938] [Fix Content Style] Language drop-down

---

elements/options-list.js
mixins/common-mixin.js
package-lock.json
package.json

[ch29278] [Fix dropdown closing] Engagement Overview: PO Item drop-down intermittently not closing when opening another drop-down

[ch29278] [Fix dropdown closing] Engagement Overview: PO Item drop-down intermittently not closing when opening another drop-down

---

package-lock.json
package.json
styles/esmm-shared-styles.js

[ch29653] [ch29734] Increase dropdown z-index

---

.npmignore
EtoolsDropdown.js
EtoolsDropdownMulti.js
README.md
assets/translations/all.js
elements/searchbox-input.js
package-lock.json
package.json
utils/translate.js

[ch30765]Localize component

---

elements/options-list.js
package-lock.json
package.json

[ch31188] Flash of horizontal scroll

[ch31188] Flash of horizontal scroll

---

src_ts/EtoolsDropdown.ts
src_ts/elements/searchbox-input.ts

[ch31232]Fix selected value not displayed & search not working intermittently

---

src_ts/mixins/common-mixin.ts

[ch32162] Intermittent Overlapping dropdowns

[ch32162] Intermittent Overlapping dropdowns

---

src_ts/mixins/common-mixin.ts

[ch32197] When searching/making a selection the dropdown list moves too far from the input field

[ch32197] When searching/making a selection the dropdown list moves too far from the input field

---

package-lock.json
package.json
src_ts/EtoolsDropdown.ts
src_ts/EtoolsDropdownMulti.ts
src_ts/elements/options-list.ts
src_ts/mixins/common-mixin.ts

[ch32097] Countries dropdown doesn't go to item that starts with the pressed letter

[ch32097] Countries dropdown doesn't go to item that starts with the pressed letter

---

package-lock.json
package.json
src_ts/EtoolsDropdown.ts
src_ts/elements/selected-options.ts

[ch32168] Tooltips on Add Programme Document no longer working

[ch32168] Tooltips on Add Programme Document no longer working

---

package-lock.json
package.json
src_ts/EtoolsDropdown.ts
src_ts/mixins/common-mixin.ts

[ch32725] Tab navigation on dropdowns not working properly

[ch32725] Tab navigation on dropdowns not working properly

---

package-lock.json
package.json
src_ts/mixins/common-mixin.ts

[ch32765] Add attachment dialog: attachment type dropdown list is not responsive

[ch32765] Add attachment dialog: attachment type dropdown list is not responsive

---

package-lock.json
package.json
src_ts/mixins/common-mixin.ts

[ch33096]Fix x btn for unselect not working

---

package-lock.json
package.json
src_ts/assets/translations.ts
src_ts/mixins/common-mixin.ts

[ch33103]Add Spanish and Arabic translations

---

package-lock.json
package.json
src_ts/elements/options-list.ts
src_ts/mixins/common-mixin.ts

[ch32098] Improve virtual scroll behaviour for the dropdown

[ch32098] Improve virtual scroll behaviour for the dropdown

---

package-lock.json
package.json
src_ts/mixins/common-mixin.ts

[ch33149]  Multi select dropdown: dropdown list size is reduced to no details displayed

[ch33149] Multi select dropdown: dropdown list size is reduced to no details displayed

---

package-lock.json
package.json
src_ts/mixins/common-mixin.ts

[ch33296] Multi select dropdown Search input covered by app header

[ch33296] Multi select dropdown Search input covered by app header

---

package-lock.json
package.json

[ch33356]Fix security warn
